# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: image_service_async.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19image_service_async.proto\"7\n\x12ImageUploadRequest\x12\x13\n\x0bimage_chunk\x18\x01 \x01(\x0c\x12\x0c\n\x04name\x18\x02 \x01(\t\"&\n\x13ImageUploadResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"$\n\x14ImageDownloadRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\",\n\x15ImageDownloadResponse\x12\x13\n\x0bimage_chunk\x18\x01 \x01(\x0c\x32\x9c\x01\n\x0cImageService\x12\x42\n\x11StreamUploadImage\x12\x13.ImageUploadRequest\x1a\x14.ImageUploadResponse\"\x00(\x01\x12H\n\x13StreamDownloadImage\x12\x15.ImageDownloadRequest\x1a\x16.ImageDownloadResponse\"\x00\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'image_service_async_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_IMAGEUPLOADREQUEST']._serialized_start=29
  _globals['_IMAGEUPLOADREQUEST']._serialized_end=84
  _globals['_IMAGEUPLOADRESPONSE']._serialized_start=86
  _globals['_IMAGEUPLOADRESPONSE']._serialized_end=124
  _globals['_IMAGEDOWNLOADREQUEST']._serialized_start=126
  _globals['_IMAGEDOWNLOADREQUEST']._serialized_end=162
  _globals['_IMAGEDOWNLOADRESPONSE']._serialized_start=164
  _globals['_IMAGEDOWNLOADRESPONSE']._serialized_end=208
  _globals['_IMAGESERVICE']._serialized_start=211
  _globals['_IMAGESERVICE']._serialized_end=367
# @@protoc_insertion_point(module_scope)
