# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import image_service_async_pb2 as image__service__async__pb2


class ImageServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamUploadImage = channel.stream_unary(
                '/ImageService/StreamUploadImage',
                request_serializer=image__service__async__pb2.ImageUploadRequest.SerializeToString,
                response_deserializer=image__service__async__pb2.ImageUploadResponse.FromString,
                )
        self.StreamDownloadImage = channel.unary_stream(
                '/ImageService/StreamDownloadImage',
                request_serializer=image__service__async__pb2.ImageDownloadRequest.SerializeToString,
                response_deserializer=image__service__async__pb2.ImageDownloadResponse.FromString,
                )


class ImageServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def StreamUploadImage(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamDownloadImage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ImageServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StreamUploadImage': grpc.stream_unary_rpc_method_handler(
                    servicer.StreamUploadImage,
                    request_deserializer=image__service__async__pb2.ImageUploadRequest.FromString,
                    response_serializer=image__service__async__pb2.ImageUploadResponse.SerializeToString,
            ),
            'StreamDownloadImage': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamDownloadImage,
                    request_deserializer=image__service__async__pb2.ImageDownloadRequest.FromString,
                    response_serializer=image__service__async__pb2.ImageDownloadResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ImageService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ImageService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def StreamUploadImage(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(request_iterator, target, '/ImageService/StreamUploadImage',
            image__service__async__pb2.ImageUploadRequest.SerializeToString,
            image__service__async__pb2.ImageUploadResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def StreamDownloadImage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/ImageService/StreamDownloadImage',
            image__service__async__pb2.ImageDownloadRequest.SerializeToString,
            image__service__async__pb2.ImageDownloadResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
